name: plfu
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.7
  - scikit-learn
  - scipy
  - pip
  - pip:
    - pyyaml
    - tqdm
    - Pillow
    - pandas
    - matplotlib
    - psutil
