name: plfu
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-rocm=5.4.2
  - scikit-learn
  - scipy
  - pip
  - pip:
    - pyyaml
    - pyarrow
    - scikit-image
    - xgboost
    - seaborn
    - tqdm
    - Pillow
    - pandas
    - matplotlib
    - psutil
    - timm
