name: plfu
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - scikit-learn
  - scipy
  - pip
  - pip:
    - pyyaml
    - tqdm
    - Pillow
    - pandas=2.0.3
    - matplotlib
    - psutil
